### ISSUE TITLE
Bad _acme-challenge TXT record creation by certbot

### ISSUE THREAD

**Issue by fwehrle** [Infomaniak/certbot-dns-infomaniak#19]
Hi,

I try to use your cretbot-dns-infomaniak plugin with certbot in Swag proxy.
But certbot create 2 DNS TXT records named _acme-challenge.mydomain.com.mydomain.com instead of _acme-challenge.mydomain.com
So the certificat creation fail with a time out. 
Notice : if I create the 2 TXT record manually, certificate creation is working fine.

Am i the only one?

Thank you for this plugin

fwehrle

![image](https://user-images.githubusercontent.com/5674996/158213675-fb406b54-ffc6-4537-a44c-83acac6bb8b2.png)

**Comment by Fuechslein** [comment]
Probably related to my last botched PR. @reneluria would it be possible to build the plugin again with my fixes?

**Comment by reneluria** [comment]
@Fuechslein yes, sorry, did not push the tag
https://github.com/Infomaniak/certbot-dns-infomaniak/releases/tag/0.1.16
