### ISSUE TITLE
Other Port than 80

### ISSUE THREAD

**Issue by donat1** [Infomaniak/certbot-dns-infomaniak#28]
I'm not shure, but I guess, that another port than 80 won't work with this renew? What do I have to change?

**Comment by Matoran** [comment]
The purpose of this plugin is to validate your certificate with DNS. No port is used on your side. 
You can just run
```bash
export INFOMANIAK_API_TOKEN=yourtoken
certbot renew --authenticator dns-infomaniak
```
to renew it.
