### ISSUE TITLE
Conflict with Debian distro package?

### ISSUE THREAD

**Issue by ne20002** [Infomaniak/certbot-dns-infomaniak#9]
After running in the same problems with installation as AisteruFire I managed to get certbot running on my Raspberry Pi with Raspian OS buster by 

- removing my distro package (which was cerbot 0.31)
- installing python3 
- installing certbot with 'pip install certbot' (certbot 1.11)

Updating the current certificate for the server worked then and I also got a wildcard certificate using certbot-dns-infomaniak hook.

But: Now the certbot service is gone which handled automatic renewal before. Also, on the Certbot web page (https://certbot.eff.org/docs/install.html#system-requirements) is a warning *to not install via pip install* and to use the distro packages instead.
But using the distro package failed with the certbot-dns-infomaniak hook as this requires certbot >= 0.35. :(

Any idea how to solve this?

**Comment by reneluria** [comment]
Hello, I will try myself on a raspbian buster

**Comment by reneluria** [comment]
Ok the problem is with the old version of certbot shipped with buster. Installing certbot from the distro and a specific plugin via pip should not be an issue, but because of the required `>= 0.34` it installs certbot from pip over the distro one.
I just made a fix that should make it work.

**Comment by reneluria** [comment]
So you should remove all packages installed by your pip run and reinstall certbot-dns-infomaniak, this time it should only install those packages from pip:

```
Collecting certbot-dns-infomaniak
  Downloading https://files.pythonhosted.org/packages/cd/6e/3733a3a9ecbcd4069e523ba34feb2a063f76278d855a3419a26e48cbdd37/certbot_dns_infomaniak-0.1.10-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from certbot-dns-infomaniak) (40.8.0)
Requirement already satisfied: mock in /usr/lib/python3/dist-packages (from certbot-dns-infomaniak) (2.0.0)
Requirement already satisfied: certbot>=0.31.0 in /usr/lib/python3/dist-packages (from certbot-dns-infomaniak) (0.31.0)
Collecting requests-mock (from certbot-dns-infomaniak)
  Downloading https://files.pythonhosted.org/packages/40/81/fe80531c627bd0d187f2ea9158942efd16342731ac5aefa017b871b44b77/requests_mock-1.8.0-py2.py3-none-any.whl
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from certbot-dns-infomaniak) (2.21.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from requests-mock->certbot-dns-infomaniak) (1.12.0)
Installing collected packages: requests-mock, certbot-dns-infomaniak
Successfully installed certbot-dns-infomaniak-0.1.10 requests-mock-1.8.0
```

**Comment by ne20002** [comment]
Hi @reneluria 
Thank you.
